sudo: false

language: generic

env:
  - PYVER="3.5"
  - PYVER="3.4"
  - PYVER="2.7"

install:
  # Install Miniconda.
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh > miniconda.sh
  - openssl md5 miniconda.sh | grep 874dbb0d3c7ec665adf7231bbb575ab2
  - bash miniconda.sh -b -p ~/miniconda
  - rm miniconda.sh
  - source ~/miniconda/bin/activate root
  - conda config --set show_channel_urls true
  - conda update -y -n root --all
  - conda install -y -n root conda-build
  - conda clean -tipsy

  # Create the test environment.
  - conda create -y -n testenv python="${PYVER}"
  - conda remove -y --force -n testenv openssl
  - conda env update -n testenv --file environment_dev.yml
  - conda list --full-name -n testenv openssl || conda install -y -n testenv openssl
  - source activate testenv

  # Install the package and dependencies.
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - coverage erase
  - coverage run --source . setup.py test
  - coverage report

# Report coverage
after_success:
  - coveralls

# Disable email notifications.
notifications:
  email: false

# Deploy package to PyPI when tagged.
deploy:
  provider: pypi
  distributions: sdist
  user: jakirkham
  password:
    secure: O4H0EPocKWPrAJG/CNQbWMJlB16hMSDsdvJExdd5VmF4+AwIA5VcFVgFKIBEw5wSsilXWzdbsWeKB/hM9RW3PlOEJYlI+cOrVq8kT7lingFR63NzXVrnG4o0TBvjlahGyDflpDoRJ2Nrg4pNP5DDT5ABms3+hWafNHJLbNHHtk0j57jaK+lSkIlvj9YhCn3UvunanUHWGCID9YsdQzg4PKZTDglMMZxiNHYz/NOx+DdGC7GTGRxMlgj4nwsbEsTqmx5lkc7La0AVXE/m0ngqeqbmNIOlDTGCQScuWsA7f7pBQIAxfipl8BtSr3VMvYvcBFria0RlwLJfXEnGawtNYgyBa3W/le16xU+sDW9Imsz6N6KcusOmmj6M8Ai+5b59LebhGXgzYcnrUEwYkaruYtPW3WDAlMmthcV4LlcOWxou0wFXiOA6vA1hGRtu6tRNZXmJmrZPkNtbFGgQZ4lsRjfO3l69hjDSyW5Pv/6JxsoJufHVlXwVxbKvyjcbXPde9bbbrPlrAQIRwO8EdAoowpxE9yMTLcjZPATwl09yvVvZMKo32rt67sdNVfMZ+xsboyuV4OlQsBRyfUKkQzjTdjR2wZ8yQG6cMOc9EO+AfCEmcruPXH+YcLZzM+FaqqpbRv9wV8EvRT4kwWOWNg2TKD8PixL+au98GPPLK5w/iIg=
  on:
    tags: true
    repo: jakirkham/metawrap
    condition: $PYVER == 2.7
